package View;

public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Arquivo = new javax.swing.JMenu();
        MI_Sair = new javax.swing.JMenuItem();
        Menu_Curriculos = new javax.swing.JMenu();
        MI_Cadastrar_Curriculo = new javax.swing.JMenuItem();
        MI_Gerenciar_Curriculos = new javax.swing.JMenuItem();
        Menu_Vagas = new javax.swing.JMenu();
        MI_CrIar_Vaga = new javax.swing.JMenuItem();
        MI_Gerenciar_Vagas = new javax.swing.JMenuItem();
        Menu_Candidaturas = new javax.swing.JMenu();
        MI_Criar_Candidatura = new javax.swing.JMenuItem();
        MI_Gerenciar_Candidaturas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu_Arquivo.setText("Arquivo");
        Menu_Arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ArquivoActionPerformed(evt);
            }
        });

        MI_Sair.setText("Sair");
        MI_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_SairActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(MI_Sair);

        jMenuBar1.add(Menu_Arquivo);

        Menu_Curriculos.setText("Curriculos");

        MI_Cadastrar_Curriculo.setText("Cadastrar Curriculo");
        MI_Cadastrar_Curriculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_Cadastrar_CurriculoActionPerformed(evt);
            }
        });
        Menu_Curriculos.add(MI_Cadastrar_Curriculo);

        MI_Gerenciar_Curriculos.setText("Gerenciar Curriculos");
        MI_Gerenciar_Curriculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_Gerenciar_CurriculosActionPerformed(evt);
            }
        });
        Menu_Curriculos.add(MI_Gerenciar_Curriculos);

        jMenuBar1.add(Menu_Curriculos);

        Menu_Vagas.setText("Vagas");

        MI_CrIar_Vaga.setText("Criar Vaga");
        MI_CrIar_Vaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CrIar_VagaActionPerformed(evt);
            }
        });
        Menu_Vagas.add(MI_CrIar_Vaga);

        MI_Gerenciar_Vagas.setText("Gerenciar Vagas");
        MI_Gerenciar_Vagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_Gerenciar_VagasActionPerformed(evt);
            }
        });
        Menu_Vagas.add(MI_Gerenciar_Vagas);

        jMenuBar1.add(Menu_Vagas);

        Menu_Candidaturas.setText("Candidaturas");

        MI_Criar_Candidatura.setText("Criar Candidatura");
        MI_Criar_Candidatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_Criar_CandidaturaActionPerformed(evt);
            }
        });
        Menu_Candidaturas.add(MI_Criar_Candidatura);

        MI_Gerenciar_Candidaturas.setText("Gerenciar Candidaturas");
        MI_Gerenciar_Candidaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_Gerenciar_CandidaturasActionPerformed(evt);
            }
        });
        Menu_Candidaturas.add(MI_Gerenciar_Candidaturas);

        jMenuBar1.add(Menu_Candidaturas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MI_Gerenciar_CurriculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_Gerenciar_CurriculosActionPerformed
        GerenciamentoCurriculo objeto = new GerenciamentoCurriculo();
        objeto.setVisible(true);
    }//GEN-LAST:event_MI_Gerenciar_CurriculosActionPerformed

    private void MI_Criar_CandidaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_Criar_CandidaturaActionPerformed
        CadastroCandidatura objeto = new CadastroCandidatura();
        objeto.setVisible(true);
    }//GEN-LAST:event_MI_Criar_CandidaturaActionPerformed

    private void MI_Cadastrar_CurriculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_Cadastrar_CurriculoActionPerformed
        CadastroCurriculo objeto = new CadastroCurriculo();
        objeto.setVisible(true);

    }//GEN-LAST:event_MI_Cadastrar_CurriculoActionPerformed

    private void Menu_ArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ArquivoActionPerformed

    }//GEN-LAST:event_Menu_ArquivoActionPerformed

    private void MI_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MI_SairActionPerformed

    private void MI_CrIar_VagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CrIar_VagaActionPerformed
        CadastroVaga objeto = new CadastroVaga();
        objeto.setVisible(true);
    }//GEN-LAST:event_MI_CrIar_VagaActionPerformed

    private void MI_Gerenciar_VagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_Gerenciar_VagasActionPerformed
        GerenciamentoVaga objeto = new GerenciamentoVaga();
        objeto.setVisible(true);
    }//GEN-LAST:event_MI_Gerenciar_VagasActionPerformed

    private void MI_Gerenciar_CandidaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_Gerenciar_CandidaturasActionPerformed
       GerenciamentoCandidatura objeto = new GerenciamentoCandidatura();
        objeto.setVisible(true);
    }//GEN-LAST:event_MI_Gerenciar_CandidaturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MI_Cadastrar_Curriculo;
    private javax.swing.JMenuItem MI_CrIar_Vaga;
    private javax.swing.JMenuItem MI_Criar_Candidatura;
    private javax.swing.JMenuItem MI_Gerenciar_Candidaturas;
    private javax.swing.JMenuItem MI_Gerenciar_Curriculos;
    private javax.swing.JMenuItem MI_Gerenciar_Vagas;
    private javax.swing.JMenuItem MI_Sair;
    private javax.swing.JMenu Menu_Arquivo;
    private javax.swing.JMenu Menu_Candidaturas;
    private javax.swing.JMenu Menu_Curriculos;
    private javax.swing.JMenu Menu_Vagas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
